#!/bin/bash

# Author: Mo McRoberts <mo.mcroberts@bbc.co.uk>
#
# Copyright 2014-2015 BBC
# -------------------------------------------------------------------------- #
# Copyright 2010-2014, C12G Labs S.L.                                        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

## Install the context-provided SSH public key into the 'sysop' user's
## authorized_keys file.
##
## This is a (very slightly) modified version of the OpenNebula
## 02-ssh_public_key context script.

[ -z "${SSH_PUBLIC_KEY}${EC2_PUBLIC_KEY}" ] && exit 0

mkdir -m0700 -p /home/sysop/.ssh

echo -n '' > /home/sysop/.ssh/authorized_keys

if [ -n "$SSH_PUBLIC_KEY" ]; then
    echo "$SSH_PUBLIC_KEY" >> /home/sysop/.ssh/authorized_keys
fi

if [ -n "$EC2_PUBLIC_KEY" ]; then
	echo "$EC2_PUBLIC_KEY" >> /home/sysop/.ssh/authorized_keys
fi

chmod 600 /home/sysop/.ssh/authorized_keys
chown -R sysop:sysop /home/sysop/.ssh
