#! /bin/sh

# Author: Mo McRoberts <mo.mcroberts@bbc.co.uk>
#
# Copyright 2014-2015 BBC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## If /dev/vdb is present, is an ext4 partition with no disklabel and with a
## zero mount-count, re-initialise it with the label 'data' and mount it.

[ -b /dev/vdb ] || exit 0

mountcount="`/sbin/dumpe2fs -h /dev/vdb 2>/dev/null | grep -e '^Mount count:' | cut -c27-`"
# Check that there wasn't an error retrieving the filesystem information
[ x"$mountcount" = x"" ] && exit 0

# If the filesystem has previously been mounted, abort
[ $mountcount -gt 0 ] && exit 0

disklabel="`/sbin/dumpe2fs -h /dev/vdb 2>/dev/null | grep -e '^Filesystem volume name:' | cut -c27-`"
echo "disklabel=$disklabel"

# If the filesystem already has a label assigned, abort
[ x"$disklabel" = x"<none>" ] || exit 0

/sbin/mkfs.ext4 -L data /dev/vdb

exec /bin/mount /data
